# Generated by Django 5.2.17 on 2026-08-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgriCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('county', models.CharField(max_length=100)),
                ('town', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=8)),
                ('coordinates_are_approximate', models.BooleanField(default=False, help_text='True if the coordinates are a town-level estimate rather than the exact facility location.')),
                ('focus_area', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('source_note', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['county', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DiseaseCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('dairy', 'Dairy cattle'), ('crop', 'Crop')], max_length=5)),
                ('name', models.CharField(max_length=150)),
                ('affected', models.CharField(help_text='What it affects, e.g. "Dairy cattle" or a crop like "Maize", "Napier grass".', max_length=150)),
                ('icon', models.CharField(default='medkit-outline', max_length=50)),
                ('symptoms', models.TextField()),
                ('cause', models.TextField(blank=True)),
                ('prevention', models.TextField()),
                ('treatment', models.TextField()),
                ('source_note', models.CharField(blank=True, help_text='Where this guidance is drawn from, e.g. "KALRO / Kenya Veterinary Board guidance".', max_length=255)),
                ('search_terms', models.CharField(blank=True, help_text='Search phrase used to suggest related videos, e.g. "East Coast Fever cattle treatment Kenya".', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Disease catalog',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('silage', 'Silage preparation'), ('value_addition', 'Milk value addition'), ('land_prep', 'Land preparation'), ('soil_sampling', 'Soil sampling'), ('planting', 'Crop planting'), ('harvesting', 'Harvesting')], max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('icon', models.CharField(default='book-outline', max_length=50)),
                ('summary', models.CharField(max_length=255)),
                ('steps', models.TextField(help_text='One step per line.')),
                ('tips', models.TextField(blank=True, help_text='One tip per line - optional.')),
                ('source_note', models.CharField(blank=True, max_length=255)),
                ('search_terms', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
    ]
