# Generated by Django 5.2.17 on 2026-09-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0002_seed_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropSuitability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(help_text='Matches a key in farms.kenya_data.COUNTY_TOWNS.', max_length=100)),
                ('zone', models.CharField(help_text='The agro-ecological zone this recommendation is based on.', max_length=100)),
                ('crop_name', models.CharField(max_length=100)),
                ('notes', models.CharField(help_text='Why this crop suits the zone.', max_length=255)),
                ('planting_season', models.CharField(blank=True, help_text='e.g. "March-May long rains"', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Crop suitability',
                'ordering': ['county', 'crop_name'],
            },
        ),
    ]
