# Generated by Django 5.2.17 on 2026-09-10 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0004_seed_crop_suitability'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=255)),
                ('icon', models.CharField(default='school-outline', max_length=50)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='LearningLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=150)),
                ('icon', models.CharField(default='book-outline', max_length=50)),
                ('summary', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='One paragraph or bullet per line. A line starting with "## " renders as a subheading.')),
                ('key_terms', models.TextField(blank=True, help_text='One "Term: definition" per line - renders as a glossary block. Optional.')),
                ('search_terms', models.CharField(blank=True, max_length=200)),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='advisory.learningpath')),
            ],
            options={
                'ordering': ['path', 'order'],
                'unique_together': {('path', 'order')},
            },
        ),
    ]
