# Generated by Django 5.2.17 on 2026-08-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('feed', 'Feed & Nutrition'), ('veterinary', 'Veterinary'), ('labor', 'Labor / Wages'), ('equipment', 'Equipment'), ('transport', 'Transport'), ('utilities', 'Utilities'), ('sales', 'Produce Sales'), ('other', 'Other')], default='other', max_length=15),
        ),
    ]
