# Generated by Django 5.2.17 on 2026-08-19 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_transaction_options_alter_transaction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('feed', 'Feed & Nutrition'), ('veterinary', 'Veterinary'), ('labor', 'Labor / Wages'), ('equipment', 'Equipment'), ('transport', 'Transport'), ('utilities', 'Utilities'), ('water', 'Water'), ('fuel', 'Fuel'), ('sales', 'Produce Sales'), ('other', 'Other')], default='other', max_length=15),
        ),
    ]
