# Generated by Django 5.2.17 on 2026-08-30 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0004_farm_latitude_farm_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditScoreSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.PositiveSmallIntegerField()),
                ('tier', models.CharField(choices=[('poor', 'Poor'), ('fair', 'Fair'), ('good', 'Good'), ('excellent', 'Excellent')], max_length=10)),
                ('method', models.CharField(choices=[('population', 'Population PCA/KMeans'), ('provisional', 'Provisional composite (limited peer data)')], max_length=12)),
                ('population_size', models.PositiveIntegerField()),
                ('category_breakdown', models.JSONField(blank=True, default=dict)),
                ('feature_values', models.JSONField(blank=True, default=dict)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('hedera_topic_id', models.CharField(blank=True, max_length=20)),
                ('hedera_sequence_number', models.PositiveIntegerField(blank=True, null=True)),
                ('hedera_consensus_timestamp', models.CharField(blank=True, max_length=40)),
                ('hedera_anchored_at', models.DateTimeField(blank=True, null=True)),
                ('computed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_score_snapshots', to='farms.farm')),
            ],
            options={
                'ordering': ['-computed_at'],
            },
        ),
    ]
