# Generated by Django 5.2.17 on 2026-08-30 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditscore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditscoresnapshot',
            name='contributions',
            field=models.JSONField(blank=True, default=list, help_text='Exact per-feature drivers of the score - see creditscore.explain.'),
        ),
        migrations.AddField(
            model_name='creditscoresnapshot',
            name='explanation',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
