# Generated by Django 5.2.17 on 2026-09-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditscore', '0003_datapartner_datashareconsent'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapartner',
            name='contact_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='datapartner',
            name='status',
            field=models.CharField(
                choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('suspended', 'Suspended')],
                default='pending', max_length=10,
            ),
        ),
        migrations.RemoveField(
            model_name='datapartner',
            name='is_active',
        ),
    ]
