# Generated by Django 5.2.17 on 2026-09-10 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0004_farm_latitude_farm_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Stable id for the detector that produced this row.', max_length=60)),
                ('category', models.CharField(choices=[('milk', 'Milk'), ('feed', 'Feed'), ('finance', 'Finance'), ('tasks', 'Tasks'), ('inventory', 'Inventory'), ('crops', 'Crops'), ('general', 'General')], max_length=10)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=10)),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=500)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='farms.farm')),
            ],
            options={
                'ordering': ['-computed_at'],
                'unique_together': {('farm', 'key')},
            },
        ),
    ]
