# Generated by Django 5.2.17 on 2026-08-30 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0004_farm_latitude_farm_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('payload', models.JSONField()),
                ('advisory_key', models.CharField(max_length=40)),
                ('farm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weather_cache', to='farms.farm')),
            ],
        ),
    ]
