# Generated by Django 5.2.17 on 2026-08-19 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0002_crop_status_cropactivity'),
        ('inventory', '0003_alter_inventoryitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropactivity',
            name='stock_movement',
            field=models.ForeignKey(blank=True, editable=False, help_text='The produce inventory restock this harvesting activity produced.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.stockmovement'),
        ),
    ]
