# Generated by Django 5.2.17 on 2026-08-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0003_cropactivity_stock_movement'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropactivity',
            name='hedera_minted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cropactivity',
            name='hedera_serial_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cropactivity',
            name='hedera_token_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='cropactivity',
            name='hedera_transaction_id',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
