# Generated by Django 5.2.17 on 2026-09-10 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0004_cropactivity_hedera_minted_at_and_more'),
        ('geomap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='land_parcel',
            field=models.ForeignKey(blank=True, help_text='A GPS-mapped field from GeoMap, if this crop has one - preferred over field_name when set.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crops', to='geomap.landparcel'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='field_name',
            field=models.CharField(blank=True, help_text='Free-text label - used only when this crop has no mapped land_parcel below.', max_length=100),
        ),
    ]
