"""
Django settings for farm project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os

import environ
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(DEBUG=(bool, True))
# `vercel pull` writes secrets to .env.local (see Vercel's Django docs); use
# that when present, otherwise fall back to the regular gitignored .env used
# for local development.
_env_file = BASE_DIR / '.env.local'
if not _env_file.exists():
    _env_file = BASE_DIR / '.env'
environ.Env.read_env(_env_file)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='django-insecure-f&m&sa@54lk4e$o^)n(8lh!94eegzw+d9j!4+xiz@ie8ah*u++')  # type: ignore[arg-type]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1'])  # type: ignore[arg-type]
# Vercel exposes two different hostnames at runtime: VERCEL_URL is the
# unique URL of *this specific* build/deployment (changes every deploy),
# while VERCEL_PROJECT_PRODUCTION_URL is the stable production alias (e.g.
# miginonfarm.vercel.app, or a custom domain later) - the one users and the
# emailed login links actually hit. Both need to be accepted.
_vercel_hosts = [
    h for h in (os.environ.get('VERCEL_URL'), os.environ.get('VERCEL_PROJECT_PRODUCTION_URL')) if h
]
ALLOWED_HOSTS += _vercel_hosts

CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[])  # type: ignore[arg-type]
CSRF_TRUSTED_ORIGINS += [f'https://{h}' for h in _vercel_hosts]

# Vercel terminates TLS and proxies to the app over HTTP, forwarding the
# original scheme in this header - without it, request.is_secure() and every
# request.build_absolute_uri() call (used throughout the email templates for
# login/dashboard links) would wrongly resolve to http:// in production.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# The website builder shows the site in an <iframe> on our own origin. Django's
# default (DENY) turns every response in that frame - a 404, a 500, a redirect -
# into the browser's blank "refused to connect" page. SAMEORIGIN still stops any
# *other* site from framing FarmIQ (clickjacking), but lets our own pages frame
# each other, so the preview always shows what actually came back.
X_FRAME_OPTIONS = 'SAMEORIGIN'
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_SSL_REDIRECT = not DEBUG
# Start with a short HSTS window rather than the usual 1-year value - once
# HTTPS on the production domain has been confirmed stable for a while, this
# can be raised (browsers cache it, so a bad long value is hard to undo).
SECURE_HSTS_SECONDS = 0 if DEBUG else 3600


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django_countries',
    'storages',

    # Local apps
    'core',
    'accounts',
    'farms',
    'cows',
    'crops',
    'finance',
    'inventory',
    'analysis',
    'notifications',
    'tasks',
    'weather',
    'advisory',
    'blockchain',
    'creditscore',
    'website',
    'geomap',
    'insights',

    'pwa',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.DemoModeMiddleware',
    'core.middleware.TermsAcceptanceMiddleware',
]

ROOT_URLCONF = 'farm.urls'

# Custom handler for CSRF failures (stale/expired tokens, mainly) - logs the
# request for diagnosis and bounces the user onward gracefully instead of
# Django's raw 403 debug page. See accounts.views.csrf_failure.
CSRF_FAILURE_VIEW = 'accounts.views.csrf_failure'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'farms.context_processors.active_farm',
                'core.context_processors.theme',
            ],
        },
    },
]

WSGI_APPLICATION = 'farm.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# DATABASE_URL is set by Vercel (Neon integration) in production; falls back
# to the local SQLite file when it's absent, e.g. plain `manage.py runserver`.
DATABASES = {
    'default': env.db('DATABASE_URL', default=f'sqlite:///{BASE_DIR / "db.sqlite3"}')  # type: ignore[arg-type]
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

LANGUAGES = [
    ('en', 'English'),
    ('sw', 'Kiswahili'),
]

LOCALE_PATHS = [BASE_DIR / 'locale']

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
# Vercel runs `collectstatic` into STATIC_ROOT automatically during the build
# and serves the result from its CDN - no extra config needed on our side.
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# --- Media storage (S3) -------------------------------------------------------
# Vercel's filesystem is ephemeral serverless (see the comment on
# website.models.SitePage), so every uploaded image (farm site photos, and
# any future user upload) needs real persistent storage rather than
# MEDIA_ROOT. AWS_STORAGE_BUCKET_NAME being unset (local dev with no .env
# entry) is the signal that S3 isn't configured yet - MEDIA_ROOT above stays
# the fallback in that case, so `manage.py test`/local uploads keep working
# without AWS credentials. See .env.example for what to fill in.
AWS_ACCESS_KEY_ID = env('AWS_ACCESS_KEY_ID', default='')  # type: ignore[arg-type]
AWS_SECRET_ACCESS_KEY = env('AWS_SECRET_ACCESS_KEY', default='')  # type: ignore[arg-type]
AWS_STORAGE_BUCKET_NAME = env('AWS_STORAGE_BUCKET_NAME', default='')  # type: ignore[arg-type]
AWS_S3_REGION_NAME = env('AWS_S3_REGION_NAME', default='us-east-1')  # type: ignore[arg-type]
AWS_S3_CUSTOM_DOMAIN = env('AWS_S3_CUSTOM_DOMAIN', default='')  # type: ignore[arg-type]

if AWS_STORAGE_BUCKET_NAME:
    AWS_DEFAULT_ACL = None  # bucket policy/ownership settings decide access, not per-object ACLs
    AWS_S3_FILE_OVERWRITE = False
    AWS_QUERYSTRING_AUTH = False
    AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}
    STORAGES = {
        'default': {'BACKEND': 'storages.backends.s3.S3Storage'},
        'staticfiles': {'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage'},
    }
    _s3_domain = AWS_S3_CUSTOM_DOMAIN or f'{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com'
    MEDIA_URL = f'https://{_s3_domain}/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- FarmIQ project settings -----------------------------------------

AUTH_USER_MODEL = 'accounts.User'

LOGIN_URL = 'accounts:login_farm'
LOGIN_REDIRECT_URL = 'farms:dashboard'
LOGOUT_REDIRECT_URL = 'core:landing'

# Email
# In development (no .env), OTP/welcome/report emails just print to the
# console. Production sends through Resend (see core/resend_backend.py) -
# the real API key lives only in .env / the host's env vars, never here.
EMAIL_BACKEND = env('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')  # type: ignore[arg-type]
EMAIL_HOST = env('EMAIL_HOST', default='smtp.resend.com')  # type: ignore[arg-type]
EMAIL_PORT = env.int('EMAIL_PORT', default=587)
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')  # type: ignore[arg-type]
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')  # type: ignore[arg-type]
# Production sends through Resend's HTTP API, with ZeptoMail's API as a
# fallback if Resend fails: EMAIL_BACKEND=core.email_backends.FallbackEmailBackend
# (tries EMAIL_FALLBACK_BACKENDS in order). Or point EMAIL_BACKEND at either
# provider's backend directly. DEFAULT_FROM_EMAIL must be on a domain verified
# with each provider.
RESEND_API_KEY = env('RESEND_API_KEY', default='')  # type: ignore[arg-type]
ZEPTOMAIL_API_TOKEN = env('ZEPTOMAIL_API_TOKEN', default='')  # type: ignore[arg-type]
ZEPTOMAIL_API_HOST = env('ZEPTOMAIL_API_HOST', default='api.zeptomail.com')  # type: ignore[arg-type]
EMAIL_FALLBACK_BACKENDS = env.list('EMAIL_FALLBACK_BACKENDS', default=[  # type: ignore[arg-type]
    'core.resend_backend.ResendEmailBackend',
    'core.zeptomail.ZeptoMailAPIEmailBackend',
])
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='FarmIQ <noreply@farmiq.solutions>')  # type: ignore[arg-type]

OTP_VALIDITY_MINUTES = 10
OTP_MAX_ATTEMPTS = 5
OTP_RESEND_COOLDOWN_SECONDS = 45

MESSAGE_TAGS = {
    10: 'info',   # DEBUG
    20: 'info',   # INFO
    25: 'success',  # SUCCESS
    30: 'warning',  # WARNING
    40: 'error',    # ERROR
}

# --- Public site identity & legal documents ----------------------------------
# SITE_URL is the canonical public address. Emails can't use relative URLs
# (they're opened outside the site), so the logo and legal links in
# emails/base_email.html are built from this. TERMS_VERSION is bumped
# whenever the Terms of Service or Privacy Policy change materially; it's
# stored on each account at signup so we can show who agreed to which text.
SITE_URL = env('SITE_URL', default='https://www.farmiq.solutions').rstrip('/')  # type: ignore[union-attr]
TERMS_VERSION = '2026-09-21'
# Signed-in users who haven't accepted the current TERMS_VERSION are sent to the
# acceptance page. Off under `manage.py test` so the many existing tests that
# log in fixture users aren't all redirected; the acceptance tests switch it
# back on with override_settings.
REQUIRE_TERMS_ACCEPTANCE = env.bool('REQUIRE_TERMS_ACCEPTANCE', default='test' not in sys.argv)  # type: ignore[arg-type]
LEGAL_CONTACT_EMAIL = env('LEGAL_CONTACT_EMAIL', default='info@farmiq.solutions')  # type: ignore[arg-type]

# --- Progressive Web App (django-pwa) ---------------------------------------

PWA_APP_NAME = 'FarmIQ'
PWA_APP_DESCRIPTION = 'Smart dairy management - milk, feeding, herd, crops, inventory and finance in one app.'
PWA_APP_THEME_COLOR = '#047857'       # emerald-700, matches the app shell
PWA_APP_BACKGROUND_COLOR = '#f5f5f4'  # stone-100, matches the app background
PWA_APP_DISPLAY = 'standalone'
PWA_APP_ORIENTATION = 'any'
PWA_APP_START_URL = '/farm/'
PWA_APP_STATUS_BAR_COLOR = 'default'
PWA_APP_DEBUG_MODE = DEBUG
PWA_APP_DIR = 'ltr'
PWA_APP_LANG = 'en-US'

PWA_APP_ICONS = [
    {'src': '/static/images/icons/icon-72x72.png', 'sizes': '72x72', 'type': 'image/png'},
    {'src': '/static/images/icons/icon-96x96.png', 'sizes': '96x96', 'type': 'image/png'},
    {'src': '/static/images/icons/icon-128x128.png', 'sizes': '128x128', 'type': 'image/png'},
    {'src': '/static/images/icons/icon-144x144.png', 'sizes': '144x144', 'type': 'image/png'},
    {'src': '/static/images/icons/icon-152x152.png', 'sizes': '152x152', 'type': 'image/png'},
    {'src': '/static/images/icons/icon-192x192.png', 'sizes': '192x192', 'type': 'image/png'},
    {'src': '/static/images/icons/icon-384x384.png', 'sizes': '384x384', 'type': 'image/png'},
    {'src': '/static/images/icons/icon-512x512.png', 'sizes': '512x512', 'type': 'image/png'},
    {
        'src': '/static/images/icons/icon-512x512-maskable.png', 'sizes': '512x512',
        'type': 'image/png', 'purpose': 'maskable',
    },
]
PWA_APP_ICONS_APPLE = [
    {'src': '/static/images/icons/apple-icon-180.png', 'sizes': '180x180'},
]
PWA_APP_SPLASH_SCREEN = [
    {
        'src': '/static/images/icons/splash-640x1136.png',
        'media': '(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)',
    },
    {
        'src': '/static/images/icons/splash-750x1334.png',
        'media': '(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2)',
    },
    {
        'src': '/static/images/icons/splash-1242x2208.png',
        'media': '(device-width: 621px) and (device-height: 1104px) and (-webkit-device-pixel-ratio: 3)',
    },
    {
        'src': '/static/images/icons/splash-1125x2436.png',
        'media': '(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3)',
    },
    {
        'src': '/static/images/icons/splash-828x1792.png',
        'media': '(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2)',
    },
    {
        'src': '/static/images/icons/splash-1242x2688.png',
        'media': '(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3)',
    },
    {
        'src': '/static/images/icons/splash-1536x2048.png',
        'media': '(device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2)',
    },
    {
        'src': '/static/images/icons/splash-1668x2224.png',
        'media': '(device-width: 834px) and (device-height: 1112px) and (-webkit-device-pixel-ratio: 2)',
    },
    {
        'src': '/static/images/icons/splash-1668x2388.png',
        'media': '(device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2)',
    },
    {
        'src': '/static/images/icons/splash-2048x2732.png',
        'media': '(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2)',
    },
]

PWA_SERVICE_WORKER_PATH = str(BASE_DIR / 'static' / 'pwa' / 'serviceworker.js')

# --- Web Push (device notifications) -----------------------------------------
# VAPID identifies this server to the browser push services (Chrome/Firefox
# relays) so they'll accept pushes from it. Generated once with py_vapid
# (a pywebpush dependency) and stored in .env, never committed - see
# .env.example. Notifications targeted at a specific user (see
# notifications.services.notify's `recipient` kwarg) push through these keys;
# see notifications/push.py.
VAPID_PUBLIC_KEY = env('VAPID_PUBLIC_KEY', default='')  # type: ignore[arg-type]
VAPID_PRIVATE_KEY = env('VAPID_PRIVATE_KEY', default='')  # type: ignore[arg-type]
VAPID_ADMIN_EMAIL = env('VAPID_ADMIN_EMAIL', default='admin@farmiq.solutions')  # type: ignore[arg-type]

# --- Hedera Hashgraph ---------------------------------------------------------
# One admin/treasury account pays every fee and holds every mint - farms never
# get their own Hedera account; "who owns what" lives in FarmIQ's own database
# (see blockchain.models.FiqLedgerEntry and the hedera_* fields on Cow/
# CropActivity/MilkPrediction/Transaction). Only these two are real secrets,
# so only these two live in .env, never committed - see .env.example. The
# platform's 5 shared token/topic IDs are NOT secrets (they're public
# identifiers, same as any HashScan link) - they live in the database
# (blockchain.models.HederaConfig) and are created automatically the first
# time each is actually needed, so there's nothing to paste here for them.
HEDERA_NETWORK = env('HEDERA_NETWORK', default='testnet')  # type: ignore[arg-type]
HEDERA_OPERATOR_ID = env('HEDERA_OPERATOR_ID', default='')  # type: ignore[arg-type]
HEDERA_OPERATOR_KEY = env('HEDERA_OPERATOR_KEY', default='')  # type: ignore[arg-type]

# --- TomTom Maps (GeoMap module) -----------------------------------------
# Powers the GeoMap boundary/field surveying page (see geomap.views) - a
# custom vector style built in TomTom Maps Maker, loaded client-side with
# MapLibre GL JS. The key is visible in the browser's network tab like any
# client-side map SDK key (TomTom scopes/rate-limits it per key, not per
# request origin secrecy) - it still lives in .env, never hardcoded, so it
# can be rotated without a code change. See .env.example.
TOMTOM_API_KEY = env('TOMTOM_API_KEY', default='')  # type: ignore[arg-type]
TOMTOM_STYLE_ID = env('TOMTOM_STYLE_ID', default='')  # type: ignore[arg-type]

# --- WhatsApp (Meta Cloud API) --------------------------------------------
# Targeted notifications (see notifications.services.notify) can also go to
# WhatsApp, same opt-in tier as device push - see notifications/whatsapp.py.
# Free-form text only works within a 24h customer-initiated session window;
# anything outside that needs a pre-approved message template in the Meta
# Business account, which is set up outside this codebase. Empty by default
# like every other external integration here - notify() just skips the
# WhatsApp branch until these are filled in. See .env.example.
WHATSAPP_ACCESS_TOKEN = env('WHATSAPP_ACCESS_TOKEN', default='')  # type: ignore[arg-type]
WHATSAPP_PHONE_NUMBER_ID = env('WHATSAPP_PHONE_NUMBER_ID', default='')  # type: ignore[arg-type]
WHATSAPP_API_VERSION = env('WHATSAPP_API_VERSION', default='v20.0')  # type: ignore[arg-type]
