# Generated by Django 5.2.17 on 2026-09-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='repeat_every_days',
            field=models.PositiveIntegerField(blank=True, help_text='If set, completing this task automatically creates the next one this many days after the due date, e.g. 90 for a quarterly deworming.', null=True),
        ),
    ]
