# Generated by Django 5.2.17 on 2026-08-30 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cows', '0009_milkrecord_recorded_time'),
        ('crops', '0003_cropactivity_stock_movement'),
        ('farms', '0004_farm_latitude_farm_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HederaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cow_nft_token_id', models.CharField(blank=True, max_length=20)),
                ('harvest_nft_token_id', models.CharField(blank=True, max_length=20)),
                ('fiq_token_id', models.CharField(blank=True, max_length=20)),
                ('prediction_topic_id', models.CharField(blank=True, max_length=20)),
                ('finance_topic_id', models.CharField(blank=True, max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Hedera config',
            },
        ),
        migrations.CreateModel(
            name='MilkProductionCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_liters', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fiq_amount', models.DecimalField(decimal_places=2, help_text='total_liters * FIQ_REWARD_PER_LITER.', max_digits=12)),
                ('hedera_transaction_id', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_certificates', to='farms.farm')),
            ],
            options={
                'ordering': ['-end_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FiqLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(choices=[('cow_registered', 'Cow registered'), ('harvest_logged', 'Harvest logged'), ('milk_certificate', 'Milk production certificate')], max_length=20)),
                ('hedera_transaction_id', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cows.cow')),
                ('crop_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crops.cropactivity')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiq_ledger_entries', to='farms.farm')),
                ('milk_certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blockchain.milkproductioncertificate')),
            ],
            options={
                'verbose_name_plural': 'FIQ ledger entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
