# Generated by Django 5.2.17 on 2026-08-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hederaconfig',
            name='credit_score_topic_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
