# Generated by Django 5.2.17 on 2026-08-30 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_hederaconfig_credit_score_topic_id'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fiqledgerentry',
            name='earned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiq_earned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fiqledgerentry',
            name='period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fiqledgerentry',
            name='period_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fiqledgerentry',
            name='record_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fiqledgerentry',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tasks.task'),
        ),
        migrations.AlterField(
            model_name='fiqledgerentry',
            name='reason',
            field=models.CharField(choices=[('cow_registered', 'Cow registered'), ('harvest_logged', 'Harvest logged'), ('milk_certificate', 'Milk production certificate'), ('task_completed', 'Task completed'), ('data_recorded', 'Data recorded')], max_length=20),
        ),
    ]
