# Generated by Django 5.2.17 on 2026-08-16 08:03

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.CharField(help_text='Ear tag / ID number', max_length=30)),
                ('name', models.CharField(blank=True, max_length=60)),
                ('breed', models.CharField(blank=True, max_length=60)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('dry', 'Dry'), ('sold', 'Sold'), ('deceased', 'Deceased')], default='active', max_length=10)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_cows', to=settings.AUTH_USER_MODEL)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cows', to='farms.block')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cows', to='farms.farm')),
            ],
            options={
                'ordering': ['tag_id'],
                'unique_together': {('farm', 'tag_id')},
            },
        ),
        migrations.CreateModel(
            name='FeedingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('session', models.CharField(choices=[('AM', 'Morning'), ('NOON', 'Noon'), ('PM', 'Evening')], max_length=4)),
                ('cows_count', models.PositiveIntegerField(help_text='Cows fed in this block/session')),
                ('dairy_meal_kg', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('silage_hay_kg', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_records', to='farms.block')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_records', to='farms.farm')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeding_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'session'],
                'unique_together': {('block', 'date', 'session')},
            },
        ),
        migrations.CreateModel(
            name='MilkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('session', models.CharField(choices=[('AM', 'Morning'), ('NOON', 'Noon'), ('PM', 'Evening')], max_length=4)),
                ('liters', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_records', to='farms.block')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_records', to='farms.farm')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milk_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'session'],
                'unique_together': {('block', 'date', 'session')},
            },
        ),
    ]
