# Generated by Django 5.2.17 on 2026-08-16 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cows', '0001_initial'),
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='milkrecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='milkrecord',
            name='cow',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='milk_records', to='cows.cow'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='milkrecord',
            name='block',
            field=models.ForeignKey(help_text="Snapshot of the cow's block at the time of recording.", on_delete=django.db.models.deletion.CASCADE, related_name='milk_records', to='farms.block'),
        ),
        migrations.AlterUniqueTogether(
            name='milkrecord',
            unique_together={('cow', 'date', 'session')},
        ),
    ]
