# Generated by Django 5.2.17 on 2026-08-16 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cows', '0002_alter_milkrecord_unique_together_milkrecord_cow_and_more'),
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feedingrecord',
            name='cows',
            field=models.ManyToManyField(blank=True, related_name='feeding_records', to='cows.cow'),
        ),
        migrations.AlterField(
            model_name='feedingrecord',
            name='cows_count',
            field=models.PositiveIntegerField(default=0, help_text='Auto-filled from the cows selected below.'),
        ),
        migrations.CreateModel(
            name='CowTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('transferred_at', models.DateTimeField(auto_now_add=True)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='cows.cow')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cow_transfers', to='farms.farm')),
                ('from_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='farms.block')),
                ('to_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='farms.block')),
                ('transferred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cow_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transferred_at'],
            },
        ),
    ]
