# Generated by Django 5.2.17 on 2026-08-16 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cows', '0003_feedingrecord_cows_alter_feedingrecord_cows_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cow',
            name='category',
            field=models.CharField(choices=[('calf', 'Calf'), ('heifer', 'Heifer'), ('cow', 'Cow'), ('bull', 'Bull')], default='cow', max_length=10),
        ),
        migrations.AddField(
            model_name='cow',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male')], default='female', max_length=6),
        ),
    ]
