# Generated by Django 5.2.17 on 2026-08-19 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cows', '0004_cow_category_cow_gender'),
        ('inventory', '0003_alter_inventoryitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='milkrecord',
            name='stock_movement',
            field=models.ForeignKey(blank=True, editable=False, help_text='The Milk inventory restock this record produced - kept so editing/deleting the record can reconcile that stock movement instead of leaving it stale.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.stockmovement'),
        ),
    ]
