# Generated by Django 5.2.17 on 2026-08-19 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cows', '0005_milkrecord_stock_movement'),
        ('inventory', '0003_alter_inventoryitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedingrecord',
            name='dairy_meal_movement',
            field=models.ForeignKey(blank=True, editable=False, help_text='The Dairy Meal inventory usage this record produced.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.stockmovement'),
        ),
        migrations.AddField(
            model_name='feedingrecord',
            name='silage_hay_movement',
            field=models.ForeignKey(blank=True, editable=False, help_text='The Silage/Hay inventory usage this record produced.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.stockmovement'),
        ),
    ]
