# Generated by Django 5.2.17 on 2026-08-19 04:46, hand-edited: Django refuses
# to alter a ManyToManyField to add through= in place ("you cannot alter to
# or from M2M fields, or add or remove through= on M2M fields"), and doing it
# via the naive Remove+Add would silently drop every existing
# FeedingRecord<->Cow relationship. This instead: creates the new model,
# copies existing relationships across (splitting each record's totals
# evenly across its cows, matching cows.views._sync_feeding_cows' default),
# then swaps the field over.

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


def copy_existing_feeding_cows(apps, schema_editor):
    FeedingRecord = apps.get_model('cows', 'FeedingRecord')
    FeedingRecordCow = apps.get_model('cows', 'FeedingRecordCow')

    for record in FeedingRecord.objects.prefetch_related('cows').all():
        cows = list(record.cows.all())
        if not cows:
            continue
        count = len(cows)
        even_dairy = (record.dairy_meal_kg or Decimal('0')) / count
        even_silage = (record.silage_hay_kg or Decimal('0')) / count
        FeedingRecordCow.objects.bulk_create([
            FeedingRecordCow(
                feeding_record=record, cow=cow,
                dairy_meal_kg=even_dairy, silage_hay_kg=even_silage,
            )
            for cow in cows
        ])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cows', '0006_feedingrecord_dairy_meal_movement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedingRecordCow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dairy_meal_kg', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('silage_hay_kg', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_allocations', to='cows.cow')),
                ('feeding_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='cows.feedingrecord')),
            ],
            options={
                'unique_together': {('feeding_record', 'cow')},
            },
        ),
        migrations.RunPython(copy_existing_feeding_cows, noop_reverse),
        migrations.RemoveField(
            model_name='feedingrecord',
            name='cows',
        ),
        migrations.AddField(
            model_name='feedingrecord',
            name='cows',
            field=models.ManyToManyField(blank=True, related_name='feeding_records', through='cows.FeedingRecordCow', to='cows.cow'),
        ),
    ]
