# Generated by Django 5.2.17 on 2026-08-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cows', '0007_feedingrecordcow_alter_feedingrecord_cows'),
    ]

    operations = [
        migrations.AddField(
            model_name='cow',
            name='last_calving_date',
            field=models.DateField(blank=True, help_text='Days since calving (days in milk) is one of the strongest predictors of milk yield - used by the production analytics/prediction models.', null=True),
        ),
    ]
