# Generated by Django 5.2.17 on 2026-08-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cows', '0008_cow_last_calving_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='milkrecord',
            name='recorded_time',
            field=models.TimeField(blank=True, help_text='The actual time of day this was recorded - determines the session (AM/Noon/Evening).', null=True),
        ),
    ]
