# Generated by Django 5.2.17 on 2026-08-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cows', '0009_milkrecord_recorded_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='cow',
            name='hedera_minted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cow',
            name='hedera_serial_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cow',
            name='hedera_token_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='cow',
            name='hedera_transaction_id',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
