# Generated by Django 5.2.17 on 2026-09-10 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0002_seed_content'),
        ('cows', '0010_cow_hedera_minted_at_cow_hedera_serial_number_and_more'),
        ('farms', '0004_farm_latitude_farm_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CowHealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('vaccination', 'Vaccination'), ('treatment', 'Treatment'), ('checkup', 'Checkup'), ('other', 'Other')], max_length=15)),
                ('description', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('next_due_date', models.DateField(blank=True, help_text='For a follow-up dose/checkup, if there is one.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='cows.cow')),
                ('disease', models.ForeignKey(blank=True, help_text='Optional - link the matching advisory catalog entry if this was for a known disease.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='advisory.diseasecatalog')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cow_health_records', to='farms.farm')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cow_health_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
