# Generated by Django 5.2.17 on 2026-09-10 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cows', '0011_cowhealthrecord'),
        ('farms', '0004_farm_latitude_farm_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cow',
            name='dam',
            field=models.ForeignKey(blank=True, limit_choices_to={'gender': 'female'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calves', to='cows.cow'),
        ),
        migrations.AddField(
            model_name='cow',
            name='registration_number',
            field=models.CharField(blank=True, help_text='Breed society / pedigree registration number, if registered.', max_length=60),
        ),
        migrations.AddField(
            model_name='cow',
            name='sire',
            field=models.ForeignKey(blank=True, help_text='If the sire is in this herd. Otherwise use "External sire" below.', limit_choices_to={'gender': 'male'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sired_calves', to='cows.cow'),
        ),
        migrations.AddField(
            model_name='cow',
            name='sire_name',
            field=models.CharField(blank=True, help_text='External or AI bull not recorded in this herd, e.g. an AI code or name.', max_length=100),
        ),
        migrations.CreateModel(
            name='ReproductiveEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('heat', 'Heat observed'), ('insemination', 'Service / Insemination'), ('pregnant', 'Pregnancy confirmed'), ('open', 'Pregnancy check - not in calf'), ('dry_off', 'Dried off'), ('calved', 'Calved'), ('aborted', 'Abortion / loss')], max_length=15)),
                ('date', models.DateField()),
                ('sire_name', models.CharField(blank=True, help_text='External or AI bull, e.g. an AI code or name - used instead of/alongside the field above.', max_length=100)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reproductive_events', to='cows.cow')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reproductive_events', to='farms.farm')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reproductive_events', to=settings.AUTH_USER_MODEL)),
                ('sire', models.ForeignKey(blank=True, help_text='For a Service/Insemination event, if the bull is in this herd.', limit_choices_to={'gender': 'male'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cows.cow')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CowWeightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('method', models.CharField(choices=[('scale', 'Weighbridge/scale'), ('tape', 'Heart-girth tape'), ('visual', 'Visual estimate')], default='tape', max_length=10)),
                ('heart_girth_cm', models.DecimalField(blank=True, decimal_places=1, help_text='Tape measurement around the chest, just behind the front legs. Leave weight below blank to estimate it from this measurement.', max_digits=5, null=True)),
                ('weight_kg', models.DecimalField(decimal_places=1, help_text='Enter directly from a scale, or leave blank to estimate from the tape measurement above.', max_digits=6)),
                ('body_condition_score', models.DecimalField(blank=True, decimal_places=1, help_text='1 (emaciated) to 5 (obese), in 0.25 steps.', max_digits=2, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_records', to='cows.cow')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cow_weight_records', to='farms.farm')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cow_weight_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('cow', 'date')},
            },
        ),
    ]
