# Generated by Django 5.2.17 on 2026-08-16 08:51

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('feed', 'Feed'), ('veterinary', 'Veterinary & Medicine'), ('equipment', 'Equipment'), ('other', 'Other')], default='other', max_length=15)),
                ('unit', models.CharField(choices=[('kg', 'Kilograms'), ('l', 'Litres'), ('bags', 'Bags'), ('pcs', 'Pieces'), ('boxes', 'Boxes')], default='kg', max_length=10)),
                ('current_stock', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Get a low-stock warning at or below this level. Leave at 0 to disable.', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_inventory_items', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='farms.farm')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('farm', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('movement_type', models.CharField(choices=[('in', 'Restock (in)'), ('out', 'Usage (out)'), ('adjust', 'Correction')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='For a correction, this is the new stock level. Otherwise the amount moved.', max_digits=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='farms.farm')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.inventoryitem')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
