# Generated by Django 5.2.17 on 2026-08-16 15:20

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='stock_before',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, help_text='Snapshot of current_stock right before this movement was applied.', max_digits=10),
        ),
    ]
