# Generated by Django 5.2.17 on 2026-08-19 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stockmovement_stock_before'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('feed', 'Feed'), ('veterinary', 'Veterinary & Medicine'), ('equipment', 'Equipment'), ('produce', 'Produce'), ('other', 'Other')], default='other', max_length=15),
        ),
    ]
