# Generated by Django 5.2.17 on 2026-08-19 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0003_farm_country'),
        ('inventory', '0003_alter_inventoryitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='used_by',
            field=models.ForeignKey(blank=True, help_text='Who used/consumed this (most relevant for equipment) - separate from recorded_by, who logged the entry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_usage', to='farms.farmmembership'),
        ),
    ]
