# Generated by Django 5.2.17 on 2026-08-19 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stockmovement_used_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredients', models.JSONField(blank=True, default=list, help_text='List of {"name": ..., "percent": ...}.')),
                ('crude_protein_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Overall crude protein %, e.g. 16.0', max_digits=5, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='composition', to='inventory.inventoryitem')),
            ],
        ),
    ]
