# Generated by Django 5.2.17 on 2026-08-19 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cows', '0008_cow_last_calving_date'),
        ('farms', '0003_farm_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('cow', 'Cow'), ('block', 'Block'), ('farm', 'Farm')], max_length=10)),
                ('predicted_date', models.DateField()),
                ('predicted_liters', models.DecimalField(decimal_places=2, max_digits=7)),
                ('contributions', models.JSONField(blank=True, default=list)),
                ('explanation', models.CharField(blank=True, max_length=255)),
                ('trained_at', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='milk_predictions', to='farms.block')),
                ('cow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='milk_predictions', to='cows.cow')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_predictions', to='farms.farm')),
            ],
            options={
                'ordering': ['predicted_date'],
                'unique_together': {('farm', 'scope', 'cow', 'block', 'predicted_date')},
            },
        ),
    ]
