# Generated by Django 5.2.17 on 2026-08-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='milkprediction',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='milkprediction',
            name='hedera_anchored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='milkprediction',
            name='hedera_consensus_timestamp',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='milkprediction',
            name='hedera_sequence_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='milkprediction',
            name='hedera_topic_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
