# Generated by Django 5.2.17 on 2026-08-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmmembership',
            name='last_notifications_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
