# Generated by Django 5.2.17 on 2026-08-16 17:57

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_farmmembership_last_notifications_read_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='KE', max_length=2),
        ),
    ]
