# Generated by Django 5.2.17 on 2026-08-16 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to='farms.farm'),
        ),
        migrations.AddIndex(
            model_name='emailotp',
            index=models.Index(fields=['email', 'purpose', 'farm'], name='accounts_em_email_db74df_idx'),
        ),
    ]
