# Generated by Django 5.2.17 on 2026-08-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='purpose',
            field=models.CharField(choices=[('login', 'Login'), ('signup', 'Signup verification'), ('email_change', 'Email change verification')], max_length=15),
        ),
    ]
