# Generated by Django 5.2.17 on 2026-08-19 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_emailotp_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification_delivery',
            field=models.CharField(choices=[('in_app', 'In-app only'), ('push', 'Device notifications only'), ('both', 'Both')], default='both', help_text='How you want to be notified about things targeted at you specifically (a task assigned to you, low stock, etc.) - not the general farm activity feed.', max_length=10),
        ),
    ]
