# Generated by Django 5.2.17 on 2026-09-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_language_user_theme_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='whatsapp_notifications_enabled',
            field=models.BooleanField(default=False, help_text='Also send targeted notifications (a task assigned to you, low stock, etc.) to WhatsApp. Independent of the in-app/push preference above.'),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='In international format, e.g. +2547XXXXXXXX - required to enable WhatsApp notifications below.', max_length=20),
        ),
    ]
