# Generated by Django 5.2.17 on 2026-09-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_whatsapp_notifications_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_seen_dashboard_tour',
            field=models.BooleanField(default=False, help_text='Whether this user has already been shown the interactive dashboard walkthrough - per-user (not per-farm), so a worker invited onto an already-set-up farm still sees it once on their own first login.'),
        ),
    ]
