# Generated by Django 5.2.17 on 2026-09-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_has_seen_dashboard_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, help_text='When this user accepted the Terms of Service and Privacy Policy at signup. Empty for accounts created before acceptance was recorded, or added by a farm owner.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_version',
            field=models.CharField(blank=True, help_text='Which version of the Terms/Privacy Policy (settings.TERMS_VERSION) was accepted.', max_length=20),
        ),
    ]
