# Generated by Django 5.2.17 on 2026-08-31 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0004_farm_latitude_farm_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=150)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='website', to='farms.farm')),
            ],
        ),
        migrations.CreateModel(
            name='SitePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, help_text='Leave blank to make this the homepage.', max_length=60)),
                ('template', models.CharField(choices=[('hero', 'Hero landing'), ('article', 'Article / About'), ('verified_stats', 'Verified farm stats'), ('contact', 'Contact')], default='article', max_length=20)),
                ('headline', models.CharField(blank=True, max_length=150)),
                ('subheading', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, help_text='Link to an image hosted elsewhere.')),
                ('cta_label', models.CharField(blank=True, max_length=40)),
                ('cta_url', models.URLField(blank=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='website.farmsite')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('site', 'slug')},
            },
        ),
    ]
