# Generated by Django 5.2.17 on 2026-08-31 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepage',
            name='image',
            field=models.ImageField(blank=True, upload_to='website_pages/'),
        ),
        migrations.AlterField(
            model_name='sitepage',
            name='image_url',
            field=models.URLField(blank=True, help_text='Or link to an image already hosted elsewhere.'),
        ),
    ]
