# Generated by Django 5.2.17 on 2026-08-31 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_sitepage_image_alter_sitepage_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmsite',
            name='theme',
            field=models.CharField(choices=[('emerald', 'Emerald'), ('harvest', 'Harvest (amber)'), ('sky', 'Sky (blue)'), ('berry', 'Berry (rose)'), ('earth', 'Earth (terracotta)')], default='emerald', max_length=20),
        ),
    ]
