# Generated by Django 5.2.17 on 2026-09-10 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0004_farm_latitude_farm_longitude'),
        ('inventory', '0005_feedcomposition'),
        ('website', '0003_farmsite_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitepage',
            name='template',
            field=models.CharField(choices=[('hero', 'Hero landing'), ('article', 'Article / About'), ('verified_stats', 'Verified farm stats'), ('products', 'Produce for sale'), ('contact', 'Contact')], default='article', max_length=20),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='each', help_text='e.g. "per liter", "per kg", "per dozen"', max_length=30)),
                ('image', models.ImageField(blank=True, upload_to='website_products/')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='farms.farm')),
                ('inventory_item', models.ForeignKey(blank=True, help_text='Optional - link to the matching produce inventory item.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.inventoryitem')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buyer_name', models.CharField(max_length=100)),
                ('buyer_phone', models.CharField(max_length=20)),
                ('buyer_note', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='new', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='farms.farm')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='website.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
